### ISSUE TITLE
Change order of RGB

### ISSUE THREAD

**Issue by jurgverhoeven** [adafruit/Adafruit-WS2801-Library#19]
I have a WS2801 led strip. 
The problem is that it uses the RBG color order.
Can I change it from RGB to RBG in the library for it to work well?

**Comment by matze19999** [comment]
Take a look in the Adafruit_WS2801.h file, line 11-17.

**Comment by microbuilder** [comment]
Feel free to bring this up in the support forum, it isn't a problem with the library itself, thanks.
